language: python
sudo: ture

env:
  - LUA="lua 5.1"
  - LUA="lua 5.2"
  - LUA="lua 5.3"
  - LUA="luajit 2.0"
  - LUA="luajit 2.0 --compat 5.2"
  - LUA="luajit 2.1"
  - LUA="luajit 2.1 --compat 5.2"

before_install:
  - pip install hererocks
  - hererocks here -r^ --$LUA
  - source here/bin/activate
  - luarocks install luafilesystem
  - mkdir bin

install:
  - lua install.lua ci

script:
  - lua Test.lua
  - fl
  - cd luagy
  - fl