os.execute("chmod 777 fl.lua")
os.execute("git submodule init")
os.execute("git submodule update")
os.execute("cd luagy")
os.execute("git submodule init")
os.execute("git submodule update")
os.execute("cd ..")
os.execute("cp -R . /usr/share/folder")
os.execute("ln -s /usr/share/folder/fl.lua /usr/bin/fl")

